width: '2560'
height: '1440'
speed: '2.5'
size: '0.75'
text: 'Pause'
assets_folder: 'assets'
images:
  - 'DVDLogo.png'
  - 'CDLogo.png'
  - 'BluRayLogo.png'
color:
  - 255
  - 255
  - 255
font: 'fonts\\sans.ttf'